'use client';

import { useState } from 'react';
import { useCVStore } from '@/store/cvStore';
import { useUIStore } from '@/store/uiStore';
import { parseCV } from '@/lib/utils/cvParser';
import { useRouter } from 'next/navigation';

export const useCVParser = () => {
  const [isParsing, setIsParsing] = useState(false);
  const { createCV, updateCurrentCV } = useCVStore();
  const { addToast } = useUIStore();
  const router = useRouter();

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setIsParsing(true);
    addToast({ type: 'info', message: 'Analyzing your CV...', duration: 2000 });

    try {
      // 1. Parse text
      const parsedData = await parseCV(file);

      // 2. Create new CV container
      const newCV = createCV('modern', '#002d6b');

      // 3. Populate with parsed data
      updateCurrentCV({
        ...parsedData,
        id: newCV.id, // Keep the ID generated by store
        title: `${file.name.split('.')[0]} (Revamped)`,
      });

      addToast({ type: 'success', message: 'CV uploaded and revamped!' });

      // 4. Redirect to editor
      router.push(`/build-cv/editor?id=${newCV.id}`);

    } catch (error) {
      console.error(error);
      addToast({ type: 'error', message: 'Could not parse file. Try a text PDF or Word doc.' });
    } finally {
      setIsParsing(false);
      // Reset input
      e.target.value = '';
    }
  };

  return { handleFileUpload, isParsing };
};
